### ISSUE TITLE
Carla Amat - Installing SkyPortal again

### ISSUE THREAD

**Issue by Carla802** [grandma-collaboration/skyportal_grandma_dev#19]
Hi @Theodlz !

I know this issue is surprising because I completed the installation, but I now have a new problem. 😫 
Looking at your response under @lydie10's last opened issue, I found out that we weren't supposed to clone the skyportal repository, but our own fork instead. However, as it was asked in the Setup tutorial, 

> Clone the [SkyPortal repository](https://github.com/skyportal/skyportal) and start a new virtual environment.
`git clone https://github.com/skyportal/skyportal.git`

I had cloned the skyportal repository and launched my local SkyPortal on it. Other members from the team are also concerned by this mistake.
I then deleted my old clone and its virtual environment, and created a new one (of my fork this time). 

I thought I simply had to redo the Launch steps to run SkyPortal on this new git clone, so that's what I did, but I now have errors occuring on the `make load_demo_data` command. However, the `make run` and `make log` commands are working fine, and the Welcome page of SkyPortal is displayed on my localhost page.

Here are my logs :
[log.zip](https://github.com/grandma-collaboration/skyportal_grandma_dev/files/9941837/log.zip)

And here is the error I get when I run `make load_demo_data`.
![image](https://user-images.githubusercontent.com/113369817/200071367-93860565-01a3-449c-92fb-4de6190976fa.png)

It upsets me a little bit to struggle again on the installation, as I already had a functional SkyPortal on my old git clone, and I don't understand why it won't work on the new on... 

I am really hoping you can help me with this error so I can get back as soon as possible at the [Adding new features](https://skyportal.io/docs/adding_features.html) tutorial, which I was almost finished with !

Thank you for your help 🙏

**Comment by mcoughlin** [comment]
@Carla802 Looks like it is working, you just need to run

make db_clear

since your database already has information in it.

Then you can run

make load_demo_data

**Comment by Carla802** [comment]
Thank you for your quick response @mcoughlin !

I had already tried make db_clear, then make db_init and finally run & make load_demo_data, but it still wasn't working.

I just tried make db_clear, run and make load_demo_data and this error still appears : 
![image](https://user-images.githubusercontent.com/113369817/200076126-76e4cbe4-5f3b-4abc-ba63-01cdbcffd7fa.png)

Everything else seems to be working fine, I don't know what the problem is.

**Comment by mcoughlin** [comment]
@Carla802 Ah yeah indeed. What does 

make log

say at the same time? Looks like the gcn_events are giving particular issues.

**Comment by Carla802** [comment]
Here are the logs when make load_demo_data fails  :
![image](https://user-images.githubusercontent.com/113369817/200077904-fc6fe45c-8d60-4b5c-b540-38c942c885ef.png)

**Comment by mcoughlin** [comment]
@Carla802 But further up I assume there are failures (maybe)? Usually we see long stack traces.

**Comment by Carla802** [comment]
No from what I see it is mostly warnings and other stuffs... The only weird message I see is the SQL one on the last screenshot : 

![image](https://user-images.githubusercontent.com/113369817/200082264-cf1ec340-e779-48fc-8d19-9d66209e8cb4.png)

![image](https://user-images.githubusercontent.com/113369817/200082325-97755020-6fba-4f2b-a547-a2cdfb0ae30e.png)

![image](https://user-images.githubusercontent.com/113369817/200082378-3f7ef048-c86b-44df-894f-4913ab8ff769.png)

**Comment by mcoughlin** [comment]
@Carla802 super interesting... so what does the home page look like? I wonder if its a weird issue where you just run out of memory at some point.

**Comment by Theodlz** [comment]
Hi @Carla802 . Well at least SkyPortal does start up, so that's not too bad of a problem!

Out of curiosity. What happens if you re run make load_demo_data right after if failed? You will naturally see a bunch of errors saying that stuff already exists in the DB, but you might succeed in uploading the rest that failed the first time. (No you dont do any make db_clear or whatever in between, no restarting the app, just giving it a second to finish what it was doing an you rerun the command again)

**Comment by Carla802** [comment]
@mcoughlin The home page of SkyPortal looks like this : 

![image](https://user-images.githubusercontent.com/113369817/200115601-142ee4f3-20fe-443b-bf9d-ccabdc0c8d2a.png)



@Theodlz When I try to re run make load demo data after it failed, my logs look like this at the same time : 

![image](https://user-images.githubusercontent.com/113369817/200114511-81693b42-8577-4ff1-b1f9-8415dff65c2e.png)

![image](https://user-images.githubusercontent.com/113369817/200114693-49da735f-164a-42ef-b922-ea3eae6eee66.png)


And the make load demo data fails again but this time with more listed files... 😢 

![image](https://user-images.githubusercontent.com/113369817/200114849-8ee880b1-b030-4f4b-903e-6b41677c077a.png)

I don't know what to try anymore...

**Comment by Theodlz** [comment]
Hi @Carla802 ! Sorry I didn't get the chance to look at your issue yet. I'll have a good luck at it in an hour from now!

**Comment by mcoughlin** [comment]
@Carla802 and if you click on the google login?

**Comment by Theodlz** [comment]
Ok so. Looking at your first failure:

- It's not so weird. It happens to me from time to time that photometry isn't added properly, or a gcn event. For the gcnevents we have had these issues in the past, so as Michael said it can happen especially if your machine isn't top-notch.
- Failure or not, when you access the front (after clicking the button to connect with google, with btw just so you know won't actually use google. While developing the app this step is automatically skipped) can you see the dashboard, sources, etc?

Second failure (when you do it again right after it failed, without restarting the app or anything):

- Errors will occur, simply because the data already exists in the DB. Now you could indeed expect that at least the gcn events that did not get added the first time might have been added. Could you check if some of them were posted in the make load_demo_data? (going up, you'll find a line with gcn_events: .... if it worked. When an entry is added, you see a dot ".", when it failed an "X".

Now, could you share with me your config? CPU, RAM, GPU, SSD, or HDD? Your setup too (VM, WSL, Proper Linux install aka Dual BOOT)

Last but not least, please discuss this with @Nayru12 and @ManonFlt which I talked with on Zoom today. They might be able to help you, especially Manon who successfully started SkyPortal.

Also, they need to share details about the tutorial (errors and missing steps) that I told them about.

Maybe we could find a day to have a quick zoom (sooner the better, tomorrow maybe?) so I can help you more easily?

**Comment by Carla802** [comment]
@mcoughlin @Theodlz To respond to both of you, when I click on the google login of the home page, it changes to a complete blank page.

Then, for the second failure, it seems that the gcn_events and earthquake couldn't be added, as you can see here.
![image](https://user-images.githubusercontent.com/113369817/200120737-44c90605-4182-4224-a40f-ad7dd57baecd.png)

Here is my config : 
CPU : AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx     2.10 GHz
Installed RAM : 8,00 Go (5,94 Go usable)
GPU : AMD Radeon(TM) Vega 8 Graphics
SSD : 117 Go and 19,6 Go free

I am running SkyPortal on  a WSL(2).

Great to hear that you helped them finish the installation ! They told us about the zoom meeting but I wasn't available at 11am. I will explain my issue to them to see if they can help me. They also explained to us what was wrong about the Adding features tutorial. 

Yes it would be great to have a quick meeting, maybe you will see more clearly my issue. Tomorrow morning sounds good to me ! At 11am (french time) ?

**Comment by Theodlz** [comment]
Sounds good to me @Carla802 . I'll send you a zoom link at 11AM.

Don't hesitate to tell others that need help to join

**Comment by Carla802** [comment]
My SkyPortal is running and the make load demo data finally worked ! It was mostly a RAM issue, I increased it and now it is working again. Thanks again for all your help, I can move on to the tutorial now. 😄
