### ISSUE TITLE
make load_demo_data not loading sources

### ISSUE THREAD

**Issue by Adiman007** [grandma-collaboration/skyportal_grandma_dev#31]
hi @mcoughlin  @Theodlz ,
I ran into a problem running the 'make load_demo_data' everything was working except the sources and few photometry.
I tried 'make db_clear && make db_init && make run' but the same thing happend.

make load_demo_data :
![make load_demo_data](https://user-images.githubusercontent.com/80261099/202254700-708ec106-a1d8-4041-bbe7-3597860c62ce.png)
![image](https://user-images.githubusercontent.com/80261099/202255397-4d44abe4-e8d6-44a7-82c1-13dba618b6c0.png)

make log : 
![image](https://user-images.githubusercontent.com/80261099/202255258-72303adf-3df3-4c31-81a7-e03b3e53afaf.png)
![image](https://user-images.githubusercontent.com/80261099/202257398-0ad43b57-f237-4dda-a9e7-7d5c09b3cf9b.png)
![image](https://user-images.githubusercontent.com/80261099/202257482-d07e76cc-f020-4c68-9393-55c3eaaa361d.png)

P.S : I can add sources manually using the buttons on the welcome page of skyportal so I can still work on the sources page using my own data but I wanted to know if it was a known bug or something :+1:

**Comment by mcoughlin** [comment]
@Adiman007 Is your branch all the way up to date with main?

**Comment by Adiman007** [comment]
yes

**Comment by mcoughlin** [comment]
@Adiman007 If you clone skyportal main, do you see the same error? I think this was fixed many commits ago.

**Comment by Theodlz** [comment]
Hi @Adiman007.

I suspect that this could be caused by the fact that you access the frontend before running the command.
Why?
Well when you access the frontend, you create a new user. What might happen is that then the ids of user posted by make load_demo_data are shifted by id.
This is only speculation, but worth a shot to clear the db, start the app and running the command without accessing the fronted in between the 2. 

Also, plus run `git log` inside of skyportal. It will show you the history of commits of the branch you are on. Please copy and paste the content of that command and post it here. Just to check if you are indeed running the latest version from main.

**Comment by Theodlz** [comment]
Hi @Adiman007, any progress? In general I would suggest you downgrade to PostgreSQL 14 to avoid errors that none of us have encountered yet.

You can look at: https://grandma-skyportal.readthedocs.io/dev_guide/
There, you'll find instructions on how to delete all installations and clusters of postgres to install version 14.
Don't forget to repeat the config steps from skyportal's docs when you are done.

**Comment by Theodlz** [comment]
Hi again @Adiman007, did you try moving to PostgreSQL 14 to see if that helps?

**Comment by Adiman007** [comment]
oh sorry since I said it like 2 weeks ago during our weekly thursday meeting I tought I closed the issue by now but I didn't (oopsie)
but yeah, in fact my github fork was updated on my github page but I didn't pull the updated branch on my computer, sorry.
